In [2]:
import numpy as np

## **Random Seed**

---

Random seed makes sure the random numbers are reproducible(i.e the same) every time the cell is run, even when the notebook is shared with someone else 

In [3]:
# Always generates psuedo random that change on every run of the cell
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[1, 9, 6],
       [3, 5, 0],
       [5, 3, 0],
       [2, 1, 4],
       [9, 5, 9]])

In [4]:
# the seed generates a psuedo random array that doesn't change. i.e reproducable
np.random.seed(seed=0)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [5]:
# the seed number doesn't matter. it just makes the random generation reproducable
np.random.seed(seed=67)
random_array5 = np.random.randint(10, size=(5,3))
random_array5

array([[3, 5, 5],
       [7, 9, 9],
       [3, 6, 9],
       [3, 7, 8],
       [5, 3, 6]])

In [6]:
np.random.seed(seed=8)
random_array6 = np.random.rand(5,3)
random_array6

array([[0.8734294 , 0.96854066, 0.86919454],
       [0.53085569, 0.23272833, 0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467],
       [0.4783918 , 0.55535647, 0.54338602],
       [0.76089558, 0.71237457, 0.6196821 ]])

## **Viewing Arrays & Matrices**

---

In [7]:
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

### Viewing unique elements of an array

In [8]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Generating a few arrays & matrices

In [9]:
np.random.seed(seed=1)
a1 = np.random.randint(4, size=(3))
a1

array([1, 3, 0])

In [10]:
np.random.seed(seed=2)
a2 = np.random.rand(2,3).round(1)
a2

array([[0.4, 0. , 0.5],
       [0.4, 0.4, 0.3]])

In [11]:
np.random.seed(seed=3)
a3 = np.random.randint(20, size=(2,3,3))
a3

array([[[10,  3,  8],
        [ 0, 19, 10],
        [11,  9, 10]],

       [[ 6,  0, 12],
        [ 7, 14, 17],
        [ 2,  2,  1]]])

### Using indexing & slicing to view the array/matrices

In [12]:
a1[0]

1

In [13]:
a2[0]

array([0.4, 0. , 0.5])

In [14]:
a3[0]

array([[10,  3,  8],
       [ 0, 19, 10],
       [11,  9, 10]])

In [15]:
a3

array([[[10,  3,  8],
        [ 0, 19, 10],
        [11,  9, 10]],

       [[ 6,  0, 12],
        [ 7, 14, 17],
        [ 2,  2,  1]]])

In [16]:
a3.shape,a3.ndim

((2, 3, 3), 3)

In [17]:
a3[:2,:2,:2]

array([[[10,  3],
        [ 0, 19]],

       [[ 6,  0],
        [ 7, 14]]])

***Numpy arrays work from the outer most size and works its way in. E.g
an array of size (2,3,4,5) means there are 5 elements in each list, there are 4 rows for the list, 3 rows of the inner row(the previous 4 rows) and finally 2 rows for the last inner row(the previous 3 rows)***


An example below

In [18]:
np.random.seed(4)
a4 = np.random.randint(20,size=(2,3,4,5))


print(a4)
print('---------------------')
print('Matrix shape is: ', a4.shape)

[[[[14  5  1  8  8]
   [18  9  7 13  8]
   [ 4 18 12  6 10]
   [ 3  0  9  6  6]]

  [[ 2 14  8 17  2]
   [ 0  8 19 10 13]
   [ 1  0 13  3 18]
   [19 15  2 18 17]]

  [[16 17  9 16 12]
   [18  3 11 18  6]
   [ 7 13 10  7  9]
   [18 19 16 15  4]]]


 [[[11 19  8  5  8]
   [ 7  0  4 11  8]
   [ 4  8 17 14  9]
   [ 4 18  3  4  7]]

  [[ 6  8  0  3 11]
   [12 10 17  1 11]
   [15 13  0 10  8]
   [ 7  6 15  8  0]]

  [[18  1 14 10 17]
   [ 3  1  3 10 16]
   [ 7 19 10  7  9]
   [15  9  3 10  2]]]]
---------------------
Matrix shape is:  (2, 3, 4, 5)


In [19]:
### Get the first 4 numbers of the inner most array

a4[:, :, :, :4]

array([[[[14,  5,  1,  8],
         [18,  9,  7, 13],
         [ 4, 18, 12,  6],
         [ 3,  0,  9,  6]],

        [[ 2, 14,  8, 17],
         [ 0,  8, 19, 10],
         [ 1,  0, 13,  3],
         [19, 15,  2, 18]],

        [[16, 17,  9, 16],
         [18,  3, 11, 18],
         [ 7, 13, 10,  7],
         [18, 19, 16, 15]]],


       [[[11, 19,  8,  5],
         [ 7,  0,  4, 11],
         [ 4,  8, 17, 14],
         [ 4, 18,  3,  4]],

        [[ 6,  8,  0,  3],
         [12, 10, 17,  1],
         [15, 13,  0, 10],
         [ 7,  6, 15,  8]],

        [[18,  1, 14, 10],
         [ 3,  1,  3, 10],
         [ 7, 19, 10,  7],
         [15,  9,  3, 10]]]])

In [20]:
### Getting only the first 3 numbers of the inner most array

a4[:, :, :, :3]

array([[[[14,  5,  1],
         [18,  9,  7],
         [ 4, 18, 12],
         [ 3,  0,  9]],

        [[ 2, 14,  8],
         [ 0,  8, 19],
         [ 1,  0, 13],
         [19, 15,  2]],

        [[16, 17,  9],
         [18,  3, 11],
         [ 7, 13, 10],
         [18, 19, 16]]],


       [[[11, 19,  8],
         [ 7,  0,  4],
         [ 4,  8, 17],
         [ 4, 18,  3]],

        [[ 6,  8,  0],
         [12, 10, 17],
         [15, 13,  0],
         [ 7,  6, 15]],

        [[18,  1, 14],
         [ 3,  1,  3],
         [ 7, 19, 10],
         [15,  9,  3]]]])

In [21]:
### Getting only the topmost list from each row

a4[:, :, :1, :]

array([[[[14,  5,  1,  8,  8]],

        [[ 2, 14,  8, 17,  2]],

        [[16, 17,  9, 16, 12]]],


       [[[11, 19,  8,  5,  8]],

        [[ 6,  8,  0,  3, 11]],

        [[18,  1, 14, 10, 17]]]])

In [22]:
a4

array([[[[14,  5,  1,  8,  8],
         [18,  9,  7, 13,  8],
         [ 4, 18, 12,  6, 10],
         [ 3,  0,  9,  6,  6]],

        [[ 2, 14,  8, 17,  2],
         [ 0,  8, 19, 10, 13],
         [ 1,  0, 13,  3, 18],
         [19, 15,  2, 18, 17]],

        [[16, 17,  9, 16, 12],
         [18,  3, 11, 18,  6],
         [ 7, 13, 10,  7,  9],
         [18, 19, 16, 15,  4]]],


       [[[11, 19,  8,  5,  8],
         [ 7,  0,  4, 11,  8],
         [ 4,  8, 17, 14,  9],
         [ 4, 18,  3,  4,  7]],

        [[ 6,  8,  0,  3, 11],
         [12, 10, 17,  1, 11],
         [15, 13,  0, 10,  8],
         [ 7,  6, 15,  8,  0]],

        [[18,  1, 14, 10, 17],
         [ 3,  1,  3, 10, 16],
         [ 7, 19, 10,  7,  9],
         [15,  9,  3, 10,  2]]]])

In [23]:
### Getting only the topmost list from the outermost row

a4[:, :1, :1, :]

array([[[[14,  5,  1,  8,  8]]],


       [[[11, 19,  8,  5,  8]]]])

In [24]:
a4.shape

(2, 3, 4, 5)

In [25]:
### Getting only the 3rd list from the outermost row

a4[:, 1:2, 2:3, :]

array([[[[ 1,  0, 13,  3, 18]]],


       [[[15, 13,  0, 10,  8]]]])

## Manipulating Arrays

### Arithmetic 

In [26]:
a1

array([1, 3, 0])

In [28]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [29]:
a1 + ones

array([2., 4., 1.])

In [30]:
a1-ones

array([ 0.,  2., -1.])

In [31]:
a1 * ones

array([1., 3., 0.])

In [32]:
a2

array([[0.4, 0. , 0.5],
       [0.4, 0.4, 0.3]])

In [33]:
a1 * a2

array([[0.4, 0. , 0. ],
       [0.4, 1.2, 0. ]])

In [34]:
a3

array([[[10,  3,  8],
        [ 0, 19, 10],
        [11,  9, 10]],

       [[ 6,  0, 12],
        [ 7, 14, 17],
        [ 2,  2,  1]]])

In [36]:
a1 / ones

array([1., 3., 0.])

In [41]:
a2 / a1

<ipython-input-41-6352b1b55a84>:1: RuntimeWarning: divide by zero encountered in true_divide
  a2 / a1


array([[0.4       , 0.        ,        inf],
       [0.4       , 0.13333333,        inf]])

In [42]:
a2 ** 2

array([[0.16, 0.  , 0.25],
       [0.16, 0.16, 0.09]])

In [43]:
np.square(a2)

array([[0.16, 0.  , 0.25],
       [0.16, 0.16, 0.09]])

In [44]:
np.add(a2,a1)

array([[1.4, 3. , 0.5],
       [1.4, 3.4, 0.3]])

In [48]:
np.log(a1)

<ipython-input-48-f50b4f369011>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([0.        , 1.09861229,       -inf])

## Aggregation

In [49]:
np.sum(a1)

4

In [50]:
sum(a1)

4

Rule of thumb: Use python methods eg `sum()` on python datatypes and use numpy methods eg `np.sum()` on numpy arrays

In [51]:
# create a msive array

massive_array = np.random.random(100000)

In [52]:
massive_array.size

100000

In [54]:
massive_array[:10]

array([0.37110618, 0.13692582, 0.11251033, 0.07228326, 0.19323909,
       0.0029266 , 0.87679286, 0.93713451, 0.50264808, 0.74749482])

In [56]:
%timeit sum(massive_array) # python's sum method

6.54 ms ± 77.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [57]:
%timeit np.sum(massive_array) # numpy's sum method

27 µs ± 535 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Reshaping & Transposing

In [58]:
a2

array([[0.4, 0. , 0.5],
       [0.4, 0.4, 0.3]])

In [59]:
a2.shape

(2, 3)

In [60]:
a3.shape

(2, 3, 3)

In [ ]:
# a2 * a3

# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [61]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[0.4],
        [0. ],
        [0.5]],

       [[0.4],
        [0.4],
        [0.3]]])

In [63]:
a2_reshape * a3

array([[[4. , 1.2, 3.2],
        [0. , 0. , 0. ],
        [5.5, 4.5, 5. ]],

       [[2.4, 0. , 4.8],
        [2.8, 5.6, 6.8],
        [0.6, 0.6, 0.3]]])

In [64]:
a2


array([[0.4, 0. , 0.5],
       [0.4, 0.4, 0.3]])

In [65]:
# Transpose = Switches the axis
a2.T

array([[0.4, 0.4],
       [0. , 0.4],
       [0.5, 0.3]])

In [66]:
a2.shape,a2.T.shape

((2, 3), (3, 2))

In [67]:
a3.T

array([[[10,  6],
        [ 0,  7],
        [11,  2]],

       [[ 3,  0],
        [19, 14],
        [ 9,  2]],

       [[ 8, 12],
        [10, 17],
        [10,  1]]])

In [69]:
a3.shape,a3.T.shape

((2, 3, 3), (3, 3, 2))